# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@importFrom Rcpp sourceCpp
#'@useDynLib SAGMM
NULL

mahalanobis_HD <- function(y, mu, sigma) {
    .Call('_SAGMM_mahalanobis_HD', PACKAGE = 'SAGMM', y, mu, sigma)
}

norm_HD <- function(y, mu, sigma) {
    .Call('_SAGMM_norm_HD', PACKAGE = 'SAGMM', y, mu, sigma)
}

#'@export
main_loop_C <- function(Number, Groups, PISTAR_O, MU_O, LAMBDA_O, GAMMA, X, Dimensions, SIGMA) {
    .Call('_SAGMM_main_loop_C', PACKAGE = 'SAGMM', Number, Groups, PISTAR_O, MU_O, LAMBDA_O, GAMMA, X, Dimensions, SIGMA)
}

